shopt -s checkwinsize 			    # update the window size when necessary
shopt -s histappend 				    # append to the history file
shopt -s autocd 					      # cd without using cd

HISTCONTROL=ignoreboth 			    # don't put duplicate lines or lines starting with space in the history.
HISTSIZE= HISTFILESIZE= 		    # infite history

PS1='\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

source ~/.env                   # information about the current environment
source ~/.aliases               # general aliases 
source "$FZF/key-bindings.bash" # keybindings for fzf
