# vim:foldmethod=marker

# PATH changes {{{

PATH="$HOME/configs/scripts:$PATH"
PATH="$HOME/.local/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
PATH="$PYENV_ROOT/bin:$PATH" 
export GOPATH="$HOME/Code/Go"
PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

if command -v pyenv 1>/dev/null 2>&1
then
  eval "$(pyenv init -)" # Initialise pyenv
  eval "$(pyenv virtualenv-init -)" # initialise virtualenvs
  source $(pyenv root)/completions/pyenv.zsh
fi

# }}}

# global variables {{{

export LANG="en_GB.UTF-8"
export LC_ALL="en_GB.UTF-8"
export EDITOR='nvim'
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# }}}
