# load prompt first because it is often the slowest part
# and it makes it feel like the shell loaded faster if
# you see the prompt sooner
# spaceship options {{{

autoload -U compinit promptinit
promptinit
compinit
prompt spaceship

SPACESHIP_PYENV_PREFIX="pyenv:("
SPACESHIP_PYENV_SUFFIX=") "

SPACESHIP_VENV_PREFIX="venv:("
SPACESHIP_VENV_SUFFIX=") "

SPACESHIP_BATTERY_THRESHOLD=4

# }}}

#  sourcing {{{

# set emacs mode early so we can overwrite other mappings
set -o emacs
# environment information
source ~/.env
# general aliases
source ~/.aliases

# fzf key bindings
source "$FZF/key-bindings.zsh"

autoload compinit; compinit

# zsh syntax highlighting
source "$ZSH_PLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
# zsh autosuggestions
source "$ZSH_PLUGINS/zsh-autosuggestions/zsh-autosuggestions.zsh"
# zsh history substring search
source "$ZSH_PLUGINS/zsh-history-substring-search/zsh-history-substring-search.zsh"

# }}}

# zsh options {{{ 

DISABLE_UNTRACKED_FILES_DIRTY="true"
HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="true"
watch=(notme)
LOGCHECK=60
REPORTTIME=5
WORDCHARS='`~!@#$%^&*()-_=+[{]}\|;:",<.>/?'"'"

HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

setopt autocd                   # Allow changing directories without `cd`
setopt append_history           # Dont overwrite history
setopt extended_history         # Also record time and duration of commands.
setopt share_history            # Share history between multiple shells
setopt hist_expire_dups_first   # Clear duplicates when trimming internal hist.
setopt hist_find_no_dups        # remove duplicates during searches.
setopt hist_ignore_dups         # Ignore consecutive duplicates.
setopt hist_ignore_all_dups     # Remember only one unique copy of the command.
setopt hist_reduce_blanks       # Remove superfluous blanks.
setopt hist_save_no_dups        # Omit older commands in favor of newer ones.
setopt pushd_ignore_dups        # Dont push copies of the same dir on stack.
setopt pushd_minus              # Reference stack entries with "-".
setopt extended_glob

# use ctrl-v then the key combination to get weird symbols
bindkey '^R' fzf-history-widget
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# ctrl backspace and delete for deleting words forward and back
bindkey "^H" backward-kill-word
bindkey "^[[M" kill-word

# control up/down does a fuzzy history search
HISTORY_SUBSTRING_SEARCH_FUZZY=1
bindkey "^[[1;5A" history-substring-search-up
bindkey "^[[1;5B" history-substring-search-down

# }}}
