vim.api.nvim_set_keymap("n", "<LocalLeader>w", [[:!texcount % \| grep Total -A1 \| grep -o '[0-9]\+'<enter>]], { noremap = true })
vim.api.nvim_set_keymap("n", "<LocalLeader>p", [[:!latexrun --latex-args="-shell-escape" --bibtex-cmd=biber %<enter>]], { noremap = true })
vim.api.nvim_set_keymap("n", "<LocalLeader>x", [[:!latexrun --latex-args="-shell-escape" --bibtex-cmd=bibe % --latex-cmd xelatex<enter>]], { noremap = true })
vim.api.nvim_set_keymap("n", "<LocalLeader>v", [[:!zathura "%:r".pdf & disown<enter><enter>]], { noremap = true })
vim.api.nvim_set_keymap("n", "<LocalLeader>g", [[:!cd latex.out && gnuplot *.gnuplot<enter>]], { noremap = true })
