" General Options {{{
syntax on
set encoding=utf-8
set fileformat=unix
set showcmd
set laststatus=0 ruler
set foldlevel=99 " don't fold anything when opening the file
set foldnestmax=2 " don't fold more than 2 levels deep
syn sync fromstart " make highlighting work properly?
syn sync minlines=10000
set mouse="" " the mouse is annoying
set lazyredraw " don't redraw while doing macros (super speedy bois)
set omnifunc=syntaxcomplete#Complete " enable omnicompletion

if has('nvim')
  set inccommand=nosplit " when substituting show the substition while typing
  set runtimepath+=~/.vim " also look in ~/.vim for colorschemes and the like
endif

" Text wrapping options.
set linebreak " wrap words at word boundaries instead of at at characters
set showbreak=… " show a unicode elipsis at the start of every wrapped line

" colourschemes
if 1
  " dark: https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim
  colorscheme molokai
else
  " light: https://www.vim.org/scripts/download_script.php?src_id=10153
  colorscheme summerfruit256
  set cul
endif

function Light()
  colorscheme summerfruit256
  set cul
endfunction

function Dark()
  colorscheme molokai
  set nocul
endfunction

" add some space below/above the cursor when scrolling
set scrolloff=2

" use vim defaults because its not 1960 any more
set nocompatible

" backspace over all the things
set bs=indent,eol,start

" highight a badly spelt word red
highlight clear SpellBad
highlight SpellBad ctermbg=Red 
highlight SpellCap ctermbg=DarkGrey

" highlighting for folds
highlight clear Folded
highlight Folded guifg=Black

" styling for the vertical spliters - use unicode vertical bar
set fillchars+=vert:│

" highlight .md files
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
autocmd BufNewFile,BufReadPost *.h set filetype=c

" indentation settings
set autoindent " keep the current level of indentation when you go to a newline, e.g. with o
set smarttab " back space over tab boundaries i.e. <tab><bs> will leave you where you started

" global language settings
filetype on
set softtabstop=2 tabstop=2 shiftwidth=2 expandtab " global s
set spellfile=~/.vim/spell/en.utf-8.add

" language specific settings

augroup language_settings
  autocmd!
  autocmd Filetype tex setlocal spell
  autocmd Filetype php,c,cpp,java setlocal cin fdm=syntax
  autocmd Filetype c setlocal noet " this is because of the suckless style guide
  autocmd Filetype python setlocal ts=4 sw=4 sts=0 si fdm=indent 
         \ cinwords=if,elif,else,for,while,try,except,finally,def,class,with
  autocmd Filetype rust setlocal ts=4 sw=4 sts=0 cin fdm=syntax
  autocmd Filetype asm setlocal ts=8 sw=8 sts=0 fdm=indent noet
  autocmd FileType bib setlocal ts=6 sw=6 sts=0
  autocmd FileType markdown setlocal ts=4 sw=4 sts=0 noai spell
  autocmd FileType rmd,plaintex,mail setlocal spell
  autocmd FileType make setlocal noet fdm=indent
  autocmd FileType email setlocal tw=72
  autocmd FileType vim setlocal fdm=marker
  autocmd FileType sh,bash,zsh setlocal fdm=indent
  autocmd FileType verilog,systemverilog setlocal si fdm=indent nowrap
        \ cinwords=module,begin,function,task
augroup END

" search settings
set incsearch  " start searching as you type
set ignorecase " case insensitive searching
set smartcase  " become case sensitive if a capital is used

" splitting pane defaults
set splitbelow splitright

" }}}

" Keyboard Shortcuts and remaps {{{
" remapping arrow keys and pageup/down
if 1
  " normal mode
  nnoremap <Up> <Nop>
  nnoremap <Down> <Nop>
  nnoremap <Left> <Nop>
  nnoremap <Right> <Nop>
  nnoremap <PageUp> <Nop>
  nnoremap <PageDown> <Nop>

  " insert mode
  inoremap <Up> <Nop>
  inoremap <Down> <Nop>
  inoremap <Left> <Nop>
  inoremap <Right> <Nop>
  inoremap <PageUp> <Nop>
  inoremap <PageDown> <Nop>

  " visual mode
  vnoremap <Up> <Nop>
  vnoremap <Down> <Nop>
  vnoremap <Left> <Nop>
  vnoremap <Right> <Nop>
  vnoremap <PageUp> <Nop>
  vnoremap <PageDown> <Nop>
endif

"map F1 to escape
nnoremap <F1> <Esc>
inoremap <F1> <Esc>
vnoremap <F1> <Esc>

" fold and unfold with space
nnoremap <space> za

" add and remove words to the spelling dictionary
" add word
nnoremap <leader>g zg
" remove word
nnoremap <leader>b zw

" switch tabs
" next
nnoremap = :tabn<CR>
nnoremap L :tabn<CR>
" previous
nnoremap - :tabp<CR> 
nnoremap H :tabp<CR> 

" Copy text to the clipboard directly
vmap <C-c> "+yi
vmap <C-x> "+c
" Paste text from the clipboard directly
vmap <C-v> <ESC>"+p
imap <C-v> <ESC>"+pa

" random leader commands
nnoremap <leader>n /<++><CR>ca<
nnoremap <leader>t :!nohup st&>/dev/null&\!<CR><CR>

" awesome line to toggle highlighting after a search but only until the next
" one so each consecutive search will be highlighted but only the current
" search can be toggled
nnoremap <silent><expr> <Leader>h (&hls && v:hlsearch ? ':nohls' : ':set hls')."\n"

" toggle paste mode on / off
nnoremap <silent><expr> <Leader>v (&paste ? ':set nopaste' : ':set paste')."\n"

" shortcut automatically making a PDF in each of RMarkdown, Markdown and LaTeX
augroup pdf_mappings
  autocmd!
  autocmd FileType tex nnoremap <leader>w :!detex % \| wc -w<CR>
  autocmd FileType tex nnoremap <leader>p :!latexrun %<CR>
  autocmd FileType markdown nnoremap <leader>p :!pandoc % -s -o "%:r".pdf<CR>
  autocmd FileType rmd nnoremap <leader>p :!echo "rmarkdown::render('<c-r>%', rmarkdown::pdf_document())" \| R --vanilla<CR>
  autocmd FileType rmd,markdown,tex nnoremap <leader>v :!zathura "%:r".pdf & disown<CR><CR>
augroup END

" }}}

" Behaviour Settings {{{
" Allow persistent undo 
set undolevels=10000
set undodir=/tmp/tritoke/vim_undo
set undofile

" Jump to last location when file is opened
augroup jump_to_previous
  autocmd!
  autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
augroup END
" }}}
