call sab#Iab('#d', '#define ')
call sab#Iab('#i', '#include <><Left>')
call sab#Iab('#I', '#include ""<Left>')
call sab#Iab('intmain', 'int main(int argc, char ** argv) {<Enter>return 0;<Enter>}<Esc>kO')
call sab#Iab('envmain', 'int main(int argc, char ** argv, char ** envp) {<Enter>return 0;<Enter>}<Esc>kO')
call sab#Iab('main', 'int main(void) {<Enter>return 0;<Enter>}<Esc>kO')
