call sab#Iab('sysout', 'System.out.println("");<Esc>2hi')
call sab#Iab('sop', 'System.out.println("");<Esc>2hi')
call sab#Iab('syserr', 'System.err.println("");<Esc>2hi')
call sab#Iab('sep', 'System.err.println("");<Esc>2hi')
call sab#Iab('main', 'public static void main(String[] args) {<Enter>}<Esc>O')
