#!/bin/bash
BACKUPFILE="/etc/dhcpd.conf.ip_forwarding_backup"

usage() {
  echo "Usage: $0 <local dns server address> <internet0> <net0>"
  exit
}

perm_error() {
  echo "This script must be run as root."
  exit
}

silent() {
  $@ >/dev/null
}

internet0=$1
net0=$2

[ "$internet0" = "" ] && usage
[ "$net0" = "" ] && usage

echo "Forwarding internet from $internet0 to $net0"
echo -n "Confirm (Y/n) "
read CONT

[[ "$CONT" =~ "[nN]" ]] && exit

# use sudo if not root
[[ $EUID -ne 0 ]] && SUDO='sudo' || SUDO=''

# Check both are valid interfaces
silent ip link show dev $internet0 || exit
silent ip link show dev $net0 || exit

# Assign static IP to net0
$SUDO ip link set up dev $net0
$SUDO ip addr add 192.168.123.100/24 dev $net0

# Enable packet forwarding
silent $SUDO sysctl "net.ipv4.conf.$internet0.forwarding=1"
silent $SUDO sysctl "net.ipv4.conf.$net0.forwarding=1"

# Enable NAT
$SUDO iptables -t nat -A POSTROUTING -o $internet0 -j MASQUERADE
$SUDO iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
$SUDO iptables -A FORWARD -i $net0 -o $internet0 -j ACCEPT

echo "You can now assign the connected computer an IP address"
echo "in the subnet 192.168.123.0/24"
