#!/bin/sh
EMOJIFILE=${XDG_DATA_HOME:-$HOME/.local/share}/gitmojis
EMOJI=$(grep -v '#' $EMOJIFILE | dmenu -l 20 | cut -d ' ' -f 1 | tr -d '\n')
if [ "$EMOJI" != "" ]
then
  echo -n $EMOJI | xclip -selection clipboard
  REASON=$(grep $EMOJI $EMOJIFILE | cut -d ' ' -f 3- | tr -d '\n')

  pgrep -x dunst >/dev/null && notify-send "$(xclip -o -selection clipboard) - $REASON copied to clipboard."
fi
