#!/bin/sh

DP1=$(xrandr | grep -E 'DP-([0-9])-1 connected' | cut -d' ' -f1)
DP2=$(xrandr | grep -E 'DP-([0-9])-2 connected' | cut -d' ' -f1)

xrandr --dpi 156 --output eDP-1 --pos 0x0 --mode 1920x1200 --rate 60 --primary \
  --output "$DP1" --off \
  --output "$DP2" --off
