#!/bin/bash

DP1=$(xrandr | grep -E 'DP-([0-9])-1 connected' | cut -d' ' -f1)
DP2=$(xrandr | grep -E 'DP-([0-9])-2 connected' | cut -d' ' -f1)

# handle the missing screens
declare -a args=()
for x in $DP1 $DP2
do
  if [ "$x" != "" ]
  then
    args+=(--output "$x" --off)
  fi
done

DPI=${1:-96}

echo "xrandr --dpi $DPI --output eDP-1 --pos 0x0 --mode 1920x1200 --rate 60 --primary ${a[@]}"
xrandr --dpi $DPI --output eDP-1 --pos 0x0 --mode 1920x1200 --rate 60 --primary ${a[@]}
echo "Xft.dpi: DPI" | xrdb -merge
