#!/bin/sh
echo '#!/usr/bin/env python
from pwn import *

pwn.context.terminal = ["st", "-e", "sh", "-c"]
GDBSCRIPT = f"""
c
"""
addr_to_offset = lambda num: pwn.cyclic_find(num.to_bytes(4, "little"))
elf = pwn.ELF("./<++>")

def start(argv=None, *a, **kw):
    """Start the exploit against the target."""
    if argv is None:
        argv = []

    if args.REMOTE:
        return remote("<++>", <++>)
    elif args.GDB:
        return gdb.debug([exe.path] + argv, gdbscript=GDBSCRIPT, *a, **kw)
    else:
        return process([exe.path] + argv, *a, **kw)

def main():
    io = start()

    io.interactive()


if __name__ == "__main__":
    main()' > pwn_template.py
chmod +x pwn_template.py
