#!/bin/bash

EDP=$(xrandr | grep -E 'eDP-?1 connected' | cut -d' ' -f1)
DP1=$(xrandr | grep -E 'DP-?([0-9])-?1 connected' | cut -d' ' -f1)
DP2=$(xrandr | grep -E 'DP-?([0-9])-?2 connected' | cut -d' ' -f1)

DPI=${1:-108}

if [ "$DP1" = "" ] || [ "$DP2" = "" ]
then
  echo "Failed to detect screens: DP1=\"$DP1\", DP2=\"$DP2\""
  exit 1
fi

echo "DPI: $DPI"
echo "$EDP: off"
echo "$DP1: pos 0x0, mode 2560x1440, rate 100"
echo "$DP2: pos 2560x0, mode 2560x1440, rate 100, primary"
xrandr --dpi "$DPI" --output "$EDP" --off \
  --output "$DP1" --pos 0x0 --mode 2560x1440 --rate 100 \
  --output "$DP2" --pos 2560x0 --mode 2560x1440 --rate 100 --primary
echo "Xft.dpi: $DPI" | xrdb -merge
