#!/bin/sh
[ "$XDG_DATA_HOME" = "" ] && XDG_DATA_HOME="$HOME/.local/share"
BOOKDIR="$XDG_DATA_HOME/books"
BOOK=$(ls $BOOKDIR | cut -d '.' -f 1 | dmenu -l 30 -p "Select the book to open: ")
[ "$BOOK" = "" ] || zathura "$BOOKDIR/$BOOK.pdf"
