#!/bin/sh

eval "$(cat $HOME/.scriptvars)"
# first give a menu of all the available machines in both .raw and .qcow2 format
VM=$(ls $VMDIR/*.qcow2 $VMDIR/*.raw 2>/dev/null | rev | cut -d '/' -f 1 | rev | dmenu -l 30 -p "Select the VM to run: ")
#[ $VM = "" ] || exit
FORMAT=$(echo $VM | rev | cut -d '.' -f 1 | rev)
echo $VM
echo $FORMAT

RAM=$(echo '256M\n512M\n1G\n2G\n4G\n6G\n8G\n10G\n12G\nother' | dmenu -l 30 -p "How much RAM do you want to allocate the virtual machine")
while [ "$(echo $RAM | egrep '^[0-9]+(G|M|K)$')" = "" ]
do
  echo "custom RAM size must be a number followed by either G, M or K. The regex used to match it is: '^[0-9]+(G|M|K)$'"
  echo -n "Enter custom RAM size: " && read RAM
done

qemu-system-x86_64 -enable-kvm -drive file="$VMDIR/$VM",format="$FORMAT" -m "$RAM"
