#!/bin/bash

echo "Warning, this will kill dhcpd and flush all iptables rules."
echo -n "Continue? (y/N) "
read CONT

[[ ! "$CONT" =~ "y" ]] && exit

# use sudo if not root
[[ $EUID -ne 0 ]] && SUDO='sudo' || SUDO=''

$SUDO iptables -F
$SUDO sysctl net.ipv4.conf.wlan0.forwarding=0
$SUDO sysctl net.ipv4.conf.enp0s31f6.forwarding=0
$SUDO ip addr del 192.168.123.100/24 dev enp0s31f6
$SUDO ip link set down dev enp0s31f6
